./benchmarks/benchmarks/aliases.fish -i s/fish/ghoti/g
./benchmarks/benchmarks/external_cmds.fish -i s/fish/ghoti/g
./benchmarks/benchmarks/seq_echo.fish -i s/fish/ghoti/g
./build_tools/diff_profiles.fish -i s/fish/ghoti/g
./build_tools/find_globals.fish -i s/fish/ghoti/g
./build_tools/fish_xgettext.fish -i s/fish/ghoti/g
./build_tools/lint.fish -i s/fish/ghoti/g
./build_tools/list_committers_since.fish -i s/fish/ghoti/g
./build_tools/style.fish -i s/fish/ghoti/g
./debian/fish-common.doc-base -i s/fish/ghoti/g
./debian/fish-common.docs -i s/fish/ghoti/g
./debian/fish-common.install -i s/fish/ghoti/g
./debian/fish-common.lintian-overrides -i s/fish/ghoti/g
./debian/fish.install -i s/fish/ghoti/g
./debian/fish.postinst -i s/fish/ghoti/g
./debian/fish.postrm -i s/fish/ghoti/g
./debian/fish.prerm -i s/fish/ghoti/g
./doc_src/cmds/fish.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_add_path.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_breakpoint_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_command_not_found.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_config.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_git_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_hg_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_indent.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_is_root_user.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_key_reader.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_mode_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_opt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_right_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_svn_prompt.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_update_completions.rst -i s/fish/ghoti/g
./doc_src/cmds/fish_vcs_prompt.rst -i s/fish/ghoti/g
./doc_src/fish_for_bash_users.rst -i s/fish/ghoti/g
./doc_src/fish_indent_lexer.py -i s/fish/ghoti/g
./etc/config.fish -i s/fish/ghoti/g
./fish.desktop -i s/fish/ghoti/g
./fish.pc.in -i s/fish/ghoti/g
./fish.png -i s/fish/ghoti/g
./fish.spec.in -i s/fish/ghoti/g
./osx/fish_debug.entitlements -i s/fish/ghoti/g
./osx/fish_term_icon.icns -i s/fish/ghoti/g
./osx/launch_fish.scpt -i s/fish/ghoti/g
./osx/osx_fish_launcher.m -i s/fish/ghoti/g
./share/completions/7z.fish -i s/fish/ghoti/g
./share/completions/7za.fish -i s/fish/ghoti/g
./share/completions/7zr.fish -i s/fish/ghoti/g
./share/completions/a2disconf.fish -i s/fish/ghoti/g
./share/completions/a2dismod.fish -i s/fish/ghoti/g
./share/completions/a2dissite.fish -i s/fish/ghoti/g
./share/completions/a2enconf.fish -i s/fish/ghoti/g
./share/completions/a2enmod.fish -i s/fish/ghoti/g
./share/completions/a2ensite.fish -i s/fish/ghoti/g
./share/completions/abbr.fish -i s/fish/ghoti/g
./share/completions/abook.fish -i s/fish/ghoti/g
./share/completions/acat.fish -i s/fish/ghoti/g
./share/completions/accept.fish -i s/fish/ghoti/g
./share/completions/ack.fish -i s/fish/ghoti/g
./share/completions/acpi.fish -i s/fish/ghoti/g
./share/completions/adb.fish -i s/fish/ghoti/g
./share/completions/adduser.fish -i s/fish/ghoti/g
./share/completions/adiff.fish -i s/fish/ghoti/g
./share/completions/alias.fish -i s/fish/ghoti/g
./share/completions/als.fish -i s/fish/ghoti/g
./share/completions/alsactl.fish -i s/fish/ghoti/g
./share/completions/alsamixer.fish -i s/fish/ghoti/g
./share/completions/amixer.fish -i s/fish/ghoti/g
./share/completions/and.fish -i s/fish/ghoti/g
./share/completions/animate.fish -i s/fish/ghoti/g
./share/completions/ansible-galaxy.fish -i s/fish/ghoti/g
./share/completions/ansible-playbook.fish -i s/fish/ghoti/g
./share/completions/ansible-vault.fish -i s/fish/ghoti/g
./share/completions/ansible.fish -i s/fish/ghoti/g
./share/completions/ant.fish -i s/fish/ghoti/g
./share/completions/apack.fish -i s/fish/ghoti/g
./share/completions/apk.fish -i s/fish/ghoti/g
./share/completions/apm.fish -i s/fish/ghoti/g
./share/completions/apropos.fish -i s/fish/ghoti/g
./share/completions/apt-build.fish -i s/fish/ghoti/g
./share/completions/apt-cache.fish -i s/fish/ghoti/g
./share/completions/apt-cdrom.fish -i s/fish/ghoti/g
./share/completions/apt-config.fish -i s/fish/ghoti/g
./share/completions/apt-extracttemplates.fish -i s/fish/ghoti/g
./share/completions/apt-file.fish -i s/fish/ghoti/g
./share/completions/apt-ftparchive.fish -i s/fish/ghoti/g
./share/completions/apt-get.fish -i s/fish/ghoti/g
./share/completions/apt-key.fish -i s/fish/ghoti/g
./share/completions/apt-listbugs.fish -i s/fish/ghoti/g
./share/completions/apt-listchanges.fish -i s/fish/ghoti/g
./share/completions/apt-mark.fish -i s/fish/ghoti/g
./share/completions/apt-move.fish -i s/fish/ghoti/g
./share/completions/apt-proxy-import.fish -i s/fish/ghoti/g
./share/completions/apt-rdepends.fish -i s/fish/ghoti/g
./share/completions/apt-setup.fish -i s/fish/ghoti/g
./share/completions/apt-show-source.fish -i s/fish/ghoti/g
./share/completions/apt-show-versions.fish -i s/fish/ghoti/g
./share/completions/apt-sortpkgs.fish -i s/fish/ghoti/g
./share/completions/apt-spy.fish -i s/fish/ghoti/g
./share/completions/apt-src.fish -i s/fish/ghoti/g
./share/completions/apt-zip-inst.fish -i s/fish/ghoti/g
./share/completions/apt-zip-list.fish -i s/fish/ghoti/g
./share/completions/apt.fish -i s/fish/ghoti/g
./share/completions/aptitude.fish -i s/fish/ghoti/g
./share/completions/arc.fish -i s/fish/ghoti/g
./share/completions/arepack.fish -i s/fish/ghoti/g
./share/completions/arp.fish -i s/fish/ghoti/g
./share/completions/as.fish -i s/fish/ghoti/g
./share/completions/asciidoctor.fish -i s/fish/ghoti/g
./share/completions/asp.fish -i s/fish/ghoti/g
./share/completions/at.fish -i s/fish/ghoti/g
./share/completions/atd.fish -i s/fish/ghoti/g
./share/completions/atom.fish -i s/fish/ghoti/g
./share/completions/atool.fish -i s/fish/ghoti/g
./share/completions/atq.fish -i s/fish/ghoti/g
./share/completions/atrm.fish -i s/fish/ghoti/g
./share/completions/aunpack.fish -i s/fish/ghoti/g
./share/completions/aura.fish -i s/fish/ghoti/g
./share/completions/awk.fish -i s/fish/ghoti/g
./share/completions/aws.fish -i s/fish/ghoti/g
./share/completions/badblocks.fish -i s/fish/ghoti/g
./share/completions/base64.fish -i s/fish/ghoti/g
./share/completions/bb-wrapper.fish -i s/fish/ghoti/g
./share/completions/bc.fish -i s/fish/ghoti/g
./share/completions/bd.fish -i s/fish/ghoti/g
./share/completions/begin.fish -i s/fish/ghoti/g
./share/completions/bg.fish -i s/fish/ghoti/g
./share/completions/bind.fish -i s/fish/ghoti/g
./share/completions/bison.fish -i s/fish/ghoti/g
./share/completions/block.fish -i s/fish/ghoti/g
./share/completions/bosh.fish -i s/fish/ghoti/g
./share/completions/bower.fish -i s/fish/ghoti/g
./share/completions/break.fish -i s/fish/ghoti/g
./share/completions/brew.fish -i s/fish/ghoti/g
./share/completions/btdownloadcurses.py.fish -i s/fish/ghoti/g
./share/completions/btdownloadheadless.py.fish -i s/fish/ghoti/g
./share/completions/btrfs.fish -i s/fish/ghoti/g
./share/completions/builtin.fish -i s/fish/ghoti/g
./share/completions/bundle.fish -i s/fish/ghoti/g
./share/completions/bunzip2.fish -i s/fish/ghoti/g
./share/completions/busctl.fish -i s/fish/ghoti/g
./share/completions/bzcat.fish -i s/fish/ghoti/g
./share/completions/bzip2.fish -i s/fish/ghoti/g
./share/completions/bzip2recover.fish -i s/fish/ghoti/g
./share/completions/bzr.fish -i s/fish/ghoti/g
./share/completions/cabal-dev.fish -i s/fish/ghoti/g
./share/completions/cabal.fish -i s/fish/ghoti/g
./share/completions/caddy.fish -i s/fish/ghoti/g
./share/completions/caffeinate.fish -i s/fish/ghoti/g
./share/completions/camcontrol.fish -i s/fish/ghoti/g
./share/completions/cancel.fish -i s/fish/ghoti/g
./share/completions/canto.fish -i s/fish/ghoti/g
./share/completions/cargo.fish -i s/fish/ghoti/g
./share/completions/castnow.fish -i s/fish/ghoti/g
./share/completions/cat.fish -i s/fish/ghoti/g
./share/completions/cd.fish -i s/fish/ghoti/g
./share/completions/cdh.fish -i s/fish/ghoti/g
./share/completions/cdrecord.fish -i s/fish/ghoti/g
./share/completions/cf.fish -i s/fish/ghoti/g
./share/completions/chgrp.fish -i s/fish/ghoti/g
./share/completions/chmod.fish -i s/fish/ghoti/g
./share/completions/chown.fish -i s/fish/ghoti/g
./share/completions/chronyc.fish -i s/fish/ghoti/g
./share/completions/chsh.fish -i s/fish/ghoti/g
./share/completions/clang++.fish -i s/fish/ghoti/g
./share/completions/clang.fish -i s/fish/ghoti/g
./share/completions/climate.fish -i s/fish/ghoti/g
./share/completions/cmark.fish -i s/fish/ghoti/g
./share/completions/code.fish -i s/fish/ghoti/g
./share/completions/colordiff.fish -i s/fish/ghoti/g
./share/completions/colorsvn.fish -i s/fish/ghoti/g
./share/completions/combine.fish -i s/fish/ghoti/g
./share/completions/command.fish -i s/fish/ghoti/g
./share/completions/commandline.fish -i s/fish/ghoti/g
./share/completions/compare.fish -i s/fish/ghoti/g
./share/completions/complete.fish -i s/fish/ghoti/g
./share/completions/composer.fish -i s/fish/ghoti/g
./share/completions/composer.phar.fish -i s/fish/ghoti/g
./share/completions/composite.fish -i s/fish/ghoti/g
./share/completions/conda.fish -i s/fish/ghoti/g
./share/completions/configure.fish -i s/fish/ghoti/g
./share/completions/conjure.fish -i s/fish/ghoti/g
./share/completions/connmanctl.fish -i s/fish/ghoti/g
./share/completions/continue.fish -i s/fish/ghoti/g
./share/completions/convert.fish -i s/fish/ghoti/g
./share/completions/cowsay.fish -i s/fish/ghoti/g
./share/completions/cowthink.fish -i s/fish/ghoti/g
./share/completions/cp.fish -i s/fish/ghoti/g
./share/completions/createdb.fish -i s/fish/ghoti/g
./share/completions/create_ap.fish -i s/fish/ghoti/g
./share/completions/cryptsetup.fish -i s/fish/ghoti/g
./share/completions/csc.fish -i s/fish/ghoti/g
./share/completions/csi.fish -i s/fish/ghoti/g
./share/completions/cupsaccept.fish -i s/fish/ghoti/g
./share/completions/cupsdisable.fish -i s/fish/ghoti/g
./share/completions/cupsenable.fish -i s/fish/ghoti/g
./share/completions/cupsreject.fish -i s/fish/ghoti/g
./share/completions/curl.fish -i s/fish/ghoti/g
./share/completions/cut.fish -i s/fish/ghoti/g
./share/completions/cvs.fish -i s/fish/ghoti/g
./share/completions/cwebp.fish -i s/fish/ghoti/g
./share/completions/cygpath.fish -i s/fish/ghoti/g
./share/completions/cygport.fish -i s/fish/ghoti/g
./share/completions/cygstart.fish -i s/fish/ghoti/g
./share/completions/darcs.fish -i s/fish/ghoti/g
./share/completions/date.fish -i s/fish/ghoti/g
./share/completions/dconf.fish -i s/fish/ghoti/g
./share/completions/dd.fish -i s/fish/ghoti/g
./share/completions/defaults.fish -i s/fish/ghoti/g
./share/completions/deno.fish -i s/fish/ghoti/g
./share/completions/df.fish -i s/fish/ghoti/g
./share/completions/dhclient.fish -i s/fish/ghoti/g
./share/completions/dhcpcd.fish -i s/fish/ghoti/g
./share/completions/diff.fish -i s/fish/ghoti/g
./share/completions/dig.fish -i s/fish/ghoti/g
./share/completions/diskutil.fish -i s/fish/ghoti/g
./share/completions/display.fish -i s/fish/ghoti/g
./share/completions/djview.fish -i s/fish/ghoti/g
./share/completions/djview4.fish -i s/fish/ghoti/g
./share/completions/dlocate.fish -i s/fish/ghoti/g
./share/completions/dmesg.fish -i s/fish/ghoti/g
./share/completions/dnf.fish -i s/fish/ghoti/g
./share/completions/doas.fish -i s/fish/ghoti/g
./share/completions/docker.fish -i s/fish/ghoti/g
./share/completions/downgrade.fish -i s/fish/ghoti/g
./share/completions/dpkg-reconfigure.fish -i s/fish/ghoti/g
./share/completions/dpkg.fish -i s/fish/ghoti/g
./share/completions/dropdb.fish -i s/fish/ghoti/g
./share/completions/du.fish -i s/fish/ghoti/g
./share/completions/dumpcap.fish -i s/fish/ghoti/g
./share/completions/duply.fish -i s/fish/ghoti/g
./share/completions/dvipdf.fish -i s/fish/ghoti/g
./share/completions/dvipdfm.fish -i s/fish/ghoti/g
./share/completions/ebuild.fish -i s/fish/ghoti/g
./share/completions/echo.fish -i s/fish/ghoti/g
./share/completions/egrep.fish -i s/fish/ghoti/g
./share/completions/eix-sync.fish -i s/fish/ghoti/g
./share/completions/eix.fish -i s/fish/ghoti/g
./share/completions/elatex.fish -i s/fish/ghoti/g
./share/completions/elixir.fish -i s/fish/ghoti/g
./share/completions/emacs.fish -i s/fish/ghoti/g
./share/completions/emaint.fish -i s/fish/ghoti/g
./share/completions/emerge.fish -i s/fish/ghoti/g
./share/completions/encfs.fish -i s/fish/ghoti/g
./share/completions/entr.fish -i s/fish/ghoti/g
./share/completions/env.fish -i s/fish/ghoti/g
./share/completions/eopkg.fish -i s/fish/ghoti/g
./share/completions/epkginfo.fish -i s/fish/ghoti/g
./share/completions/equery.fish -i s/fish/ghoti/g
./share/completions/eselect.fish -i s/fish/ghoti/g
./share/completions/etex.fish -i s/fish/ghoti/g
./share/completions/eval.fish -i s/fish/ghoti/g
./share/completions/evince.fish -i s/fish/ghoti/g
./share/completions/exec.fish -i s/fish/ghoti/g
./share/completions/exercism.fish -i s/fish/ghoti/g
./share/completions/exit.fish -i s/fish/ghoti/g
./share/completions/expand.fish -i s/fish/ghoti/g
./share/completions/ezjail-admin.fish -i s/fish/ghoti/g
./share/completions/fab.fish -i s/fish/ghoti/g
./share/completions/feh.fish -i s/fish/ghoti/g
./share/completions/ffmpeg.fish -i s/fish/ghoti/g
./share/completions/ffplay.fish -i s/fish/ghoti/g
./share/completions/ffprobe.fish -i s/fish/ghoti/g
./share/completions/fg.fish -i s/fish/ghoti/g
./share/completions/fgrep.fish -i s/fish/ghoti/g
./share/completions/figlet.fish -i s/fish/ghoti/g
./share/completions/file.fish -i s/fish/ghoti/g
./share/completions/find.fish -i s/fish/ghoti/g
./share/completions/fish.fish -i s/fish/ghoti/g
./share/completions/fish_add_path.fish -i s/fish/ghoti/g
./share/completions/fish_indent.fish -i s/fish/ghoti/g
./share/completions/fish_key_reader.fish -i s/fish/ghoti/g
./share/completions/flac.fish -i s/fish/ghoti/g
./share/completions/flatpak.fish -i s/fish/ghoti/g
./share/completions/fluxbox-remote.fish -i s/fish/ghoti/g
./share/completions/for.fish -i s/fish/ghoti/g
./share/completions/fossil.fish -i s/fish/ghoti/g
./share/completions/fsharpc.fish -i s/fish/ghoti/g
./share/completions/fsharpi.fish -i s/fish/ghoti/g
./share/completions/ftp.fish -i s/fish/ghoti/g
./share/completions/funced.fish -i s/fish/ghoti/g
./share/completions/funcsave.fish -i s/fish/ghoti/g
./share/completions/function.fish -i s/fish/ghoti/g
./share/completions/functions.fish -i s/fish/ghoti/g
./share/completions/fuser.fish -i s/fish/ghoti/g
./share/completions/fusermount.fish -i s/fish/ghoti/g
./share/completions/fzf.fish -i s/fish/ghoti/g
./share/completions/g++.fish -i s/fish/ghoti/g
./share/completions/gapplication.fish -i s/fish/ghoti/g
./share/completions/gcc.fish -i s/fish/ghoti/g
./share/completions/gdb.fish -i s/fish/ghoti/g
./share/completions/gdbus.fish -i s/fish/ghoti/g
./share/completions/gem.fish -i s/fish/ghoti/g
./share/completions/gh.fish -i s/fish/ghoti/g
./share/completions/gio.fish -i s/fish/ghoti/g
./share/completions/git.fish -i s/fish/ghoti/g
./share/completions/gitk.fish -i s/fish/ghoti/g
./share/completions/go.fish -i s/fish/ghoti/g
./share/completions/godoc.fish -i s/fish/ghoti/g
./share/completions/gofmt.fish -i s/fish/ghoti/g
./share/completions/goimports.fish -i s/fish/ghoti/g
./share/completions/golint.fish -i s/fish/ghoti/g
./share/completions/gorename.fish -i s/fish/ghoti/g
./share/completions/gpasswd.fish -i s/fish/ghoti/g
./share/completions/gpg.fish -i s/fish/ghoti/g
./share/completions/gpg1.fish -i s/fish/ghoti/g
./share/completions/gpg2.fish -i s/fish/ghoti/g
./share/completions/gphoto2.fish -i s/fish/ghoti/g
./share/completions/gprof.fish -i s/fish/ghoti/g
./share/completions/gradle.fish -i s/fish/ghoti/g
./share/completions/grep.fish -i s/fish/ghoti/g
./share/completions/gresource.fish -i s/fish/ghoti/g
./share/completions/groupadd.fish -i s/fish/ghoti/g
./share/completions/groups.fish -i s/fish/ghoti/g
./share/completions/grub-file.fish -i s/fish/ghoti/g
./share/completions/grub-install.fish -i s/fish/ghoti/g
./share/completions/grub-mkrescue.fish -i s/fish/ghoti/g
./share/completions/grunt.fish -i s/fish/ghoti/g
./share/completions/gsettings.fish -i s/fish/ghoti/g
./share/completions/gunzip.fish -i s/fish/ghoti/g
./share/completions/gv.fish -i s/fish/ghoti/g
./share/completions/gvim.fish -i s/fish/ghoti/g
./share/completions/gvimdiff.fish -i s/fish/ghoti/g
./share/completions/gzip.fish -i s/fish/ghoti/g
./share/completions/head.fish -i s/fish/ghoti/g
./share/completions/helm.fish -i s/fish/ghoti/g
./share/completions/help.fish -i s/fish/ghoti/g
./share/completions/heroku.fish -i s/fish/ghoti/g
./share/completions/hg.fish -i s/fish/ghoti/g
./share/completions/highlight.fish -i s/fish/ghoti/g
./share/completions/hikari.fish -i s/fish/ghoti/g
./share/completions/history.fish -i s/fish/ghoti/g
./share/completions/hjson.fish -i s/fish/ghoti/g
./share/completions/hledger.fish -i s/fish/ghoti/g
./share/completions/htop.fish -i s/fish/ghoti/g
./share/completions/hugo.fish -i s/fish/ghoti/g
./share/completions/hwinfo.fish -i s/fish/ghoti/g
./share/completions/i3-msg.fish -i s/fish/ghoti/g
./share/completions/iconv.fish -i s/fish/ghoti/g
./share/completions/id.fish -i s/fish/ghoti/g
./share/completions/identify.fish -i s/fish/ghoti/g
./share/completions/iex.fish -i s/fish/ghoti/g
./share/completions/if.fish -i s/fish/ghoti/g
./share/completions/ifconfig.fish -i s/fish/ghoti/g
./share/completions/ifdata.fish -i s/fish/ghoti/g
./share/completions/ifdown.fish -i s/fish/ghoti/g
./share/completions/ifup.fish -i s/fish/ghoti/g
./share/completions/import.fish -i s/fish/ghoti/g
./share/completions/imv.fish -i s/fish/ghoti/g
./share/completions/invoke-rc.d.fish -i s/fish/ghoti/g
./share/completions/ip.fish -i s/fish/ghoti/g
./share/completions/ipset.fish -i s/fish/ghoti/g
./share/completions/iptables.fish -i s/fish/ghoti/g
./share/completions/irb.fish -i s/fish/ghoti/g
./share/completions/iw.fish -i s/fish/ghoti/g
./share/completions/j.fish -i s/fish/ghoti/g
./share/completions/jbake.fish -i s/fish/ghoti/g
./share/completions/jest.fish -i s/fish/ghoti/g
./share/completions/jhipster.fish -i s/fish/ghoti/g
./share/completions/jobs.fish -i s/fish/ghoti/g
./share/completions/journalctl.fish -i s/fish/ghoti/g
./share/completions/jq.fish -i s/fish/ghoti/g
./share/completions/k3d.fish -i s/fish/ghoti/g
./share/completions/kak.fish -i s/fish/ghoti/g
./share/completions/kcmshell5.fish -i s/fish/ghoti/g
./share/completions/kdeconnect-cli.fish -i s/fish/ghoti/g
./share/completions/keepassxc-cli.fish -i s/fish/ghoti/g
./share/completions/keybase.fish -i s/fish/ghoti/g
./share/completions/kill.fish -i s/fish/ghoti/g
./share/completions/killall.fish -i s/fish/ghoti/g
./share/completions/kitchen.fish -i s/fish/ghoti/g
./share/completions/kitty.fish -i s/fish/ghoti/g
./share/completions/kldload.fish -i s/fish/ghoti/g
./share/completions/kldunload.fish -i s/fish/ghoti/g
./share/completions/la.fish -i s/fish/ghoti/g
./share/completions/latex.fish -i s/fish/ghoti/g
./share/completions/latexmk.fish -i s/fish/ghoti/g
./share/completions/launchctl.fish -i s/fish/ghoti/g
./share/completions/lein.fish -i s/fish/ghoti/g
./share/completions/less.fish -i s/fish/ghoti/g
./share/completions/light.fish -i s/fish/ghoti/g
./share/completions/ll.fish -i s/fish/ghoti/g
./share/completions/ln.fish -i s/fish/ghoti/g
./share/completions/localectl.fish -i s/fish/ghoti/g
./share/completions/locate.fish -i s/fish/ghoti/g
./share/completions/loginctl.fish -i s/fish/ghoti/g
./share/completions/logkeys.fish -i s/fish/ghoti/g
./share/completions/lp.fish -i s/fish/ghoti/g
./share/completions/lpadmin.fish -i s/fish/ghoti/g
./share/completions/lpinfo.fish -i s/fish/ghoti/g
./share/completions/lpmove.fish -i s/fish/ghoti/g
./share/completions/lpoptions.fish -i s/fish/ghoti/g
./share/completions/lppasswd.fish -i s/fish/ghoti/g
./share/completions/lpq.fish -i s/fish/ghoti/g
./share/completions/lpr.fish -i s/fish/ghoti/g
./share/completions/lprm.fish -i s/fish/ghoti/g
./share/completions/lpstat.fish -i s/fish/ghoti/g
./share/completions/ls.fish -i s/fish/ghoti/g
./share/completions/lsblk.fish -i s/fish/ghoti/g
./share/completions/lscpu.fish -i s/fish/ghoti/g
./share/completions/lsof.fish -i s/fish/ghoti/g
./share/completions/lsusb.fish -i s/fish/ghoti/g
./share/completions/lua.fish -i s/fish/ghoti/g
./share/completions/lualatex.fish -i s/fish/ghoti/g
./share/completions/lunchy.fish -i s/fish/ghoti/g
./share/completions/lxc.fish -i s/fish/ghoti/g
./share/completions/lxpanel.fish -i s/fish/ghoti/g
./share/completions/lz4.fish -i s/fish/ghoti/g
./share/completions/lz4c.fish -i s/fish/ghoti/g
./share/completions/lz4cat.fish -i s/fish/ghoti/g
./share/completions/m4.fish -i s/fish/ghoti/g
./share/completions/machinectl.fish -i s/fish/ghoti/g
./share/completions/magento.fish -i s/fish/ghoti/g
./share/completions/make.fish -i s/fish/ghoti/g
./share/completions/makedepend.fish -i s/fish/ghoti/g
./share/completions/makensis.fish -i s/fish/ghoti/g
./share/completions/makepkg.fish -i s/fish/ghoti/g
./share/completions/man.fish -i s/fish/ghoti/g
./share/completions/mariner.fish -i s/fish/ghoti/g
./share/completions/math.fish -i s/fish/ghoti/g
./share/completions/mc.fish -i s/fish/ghoti/g
./share/completions/md5sum.fish -i s/fish/ghoti/g
./share/completions/mdadm.fish -i s/fish/ghoti/g
./share/completions/mdbook.fish -i s/fish/ghoti/g
./share/completions/mddiagnose.fish -i s/fish/ghoti/g
./share/completions/mdfind.fish -i s/fish/ghoti/g
./share/completions/mdimport.fish -i s/fish/ghoti/g
./share/completions/mdls.fish -i s/fish/ghoti/g
./share/completions/mdutil.fish -i s/fish/ghoti/g
./share/completions/meson.fish -i s/fish/ghoti/g
./share/completions/micro.fish -i s/fish/ghoti/g
./share/completions/minikube.fish -i s/fish/ghoti/g
./share/completions/mix.fish -i s/fish/ghoti/g
./share/completions/mkdir.fish -i s/fish/ghoti/g
./share/completions/mkdocs.fish -i s/fish/ghoti/g
./share/completions/mkdosfs.fish -i s/fish/ghoti/g
./share/completions/mkfs.fat.fish -i s/fish/ghoti/g
./share/completions/mkfs.vfat.fish -i s/fish/ghoti/g
./share/completions/mkinitcpio.fish -i s/fish/ghoti/g
./share/completions/mktemp.fish -i s/fish/ghoti/g
./share/completions/mkvextract.fish -i s/fish/ghoti/g
./share/completions/mocha.fish -i s/fish/ghoti/g
./share/completions/mocp.fish -i s/fish/ghoti/g
./share/completions/modinfo.fish -i s/fish/ghoti/g
./share/completions/modprobe.fish -i s/fish/ghoti/g
./share/completions/mogrify.fish -i s/fish/ghoti/g
./share/completions/montage.fish -i s/fish/ghoti/g
./share/completions/mosh.fish -i s/fish/ghoti/g
./share/completions/mount.fish -i s/fish/ghoti/g
./share/completions/mpc.fish -i s/fish/ghoti/g
./share/completions/mplayer.fish -i s/fish/ghoti/g
./share/completions/mpv.fish -i s/fish/ghoti/g
./share/completions/msfconsole.fish -i s/fish/ghoti/g
./share/completions/msfdb.fish -i s/fish/ghoti/g
./share/completions/msfvenom.fish -i s/fish/ghoti/g
./share/completions/msgfmt.fish -i s/fish/ghoti/g
./share/completions/mupdf.fish -i s/fish/ghoti/g
./share/completions/mutt.fish -i s/fish/ghoti/g
./share/completions/mv.fish -i s/fish/ghoti/g
./share/completions/mvn.fish -i s/fish/ghoti/g
./share/completions/mysql.fish -i s/fish/ghoti/g
./share/completions/namei.fish -i s/fish/ghoti/g
./share/completions/native2ascii.fish -i s/fish/ghoti/g
./share/completions/nc.fish -i s/fish/ghoti/g
./share/completions/nc.openbsd.fish -i s/fish/ghoti/g
./share/completions/nc.traditional.fish -i s/fish/ghoti/g
./share/completions/ncat.fish -i s/fish/ghoti/g
./share/completions/ncdu.fish -i s/fish/ghoti/g
./share/completions/netcat.fish -i s/fish/ghoti/g
./share/completions/netctl-auto.fish -i s/fish/ghoti/g
./share/completions/netctl.fish -i s/fish/ghoti/g
./share/completions/nethack.fish -i s/fish/ghoti/g
./share/completions/networkctl.fish -i s/fish/ghoti/g
./share/completions/nextd.fish -i s/fish/ghoti/g
./share/completions/ngrok.fish -i s/fish/ghoti/g
./share/completions/nice.fish -i s/fish/ghoti/g
./share/completions/ninja.fish -i s/fish/ghoti/g
./share/completions/nl.fish -i s/fish/ghoti/g
./share/completions/nm.fish -i s/fish/ghoti/g
./share/completions/nmap.fish -i s/fish/ghoti/g
./share/completions/nmcli.fish -i s/fish/ghoti/g
./share/completions/node.fish -i s/fish/ghoti/g
./share/completions/not.fish -i s/fish/ghoti/g
./share/completions/npm.fish -i s/fish/ghoti/g
./share/completions/nvim.fish -i s/fish/ghoti/g
./share/completions/nvram.fish -i s/fish/ghoti/g
./share/completions/objdump.fish -i s/fish/ghoti/g
./share/completions/obnam.fish -i s/fish/ghoti/g
./share/completions/oggenc.fish -i s/fish/ghoti/g
./share/completions/omega.fish -i s/fish/ghoti/g
./share/completions/opam.fish -i s/fish/ghoti/g
./share/completions/open.fish -i s/fish/ghoti/g
./share/completions/openocd.fish -i s/fish/ghoti/g
./share/completions/openssl.fish -i s/fish/ghoti/g
./share/completions/opkg.fish -i s/fish/ghoti/g
./share/completions/optipng.fish -i s/fish/ghoti/g
./share/completions/or.fish -i s/fish/ghoti/g
./share/completions/p4.fish -i s/fish/ghoti/g
./share/completions/pacaur.fish -i s/fish/ghoti/g
./share/completions/pacman-color.fish -i s/fish/ghoti/g
./share/completions/pacman-key.fish -i s/fish/ghoti/g
./share/completions/pacman.fish -i s/fish/ghoti/g
./share/completions/pacmatic.fish -i s/fish/ghoti/g
./share/completions/pacmd.fish -i s/fish/ghoti/g
./share/completions/pactl.fish -i s/fish/ghoti/g
./share/completions/pactree.fish -i s/fish/ghoti/g
./share/completions/pandoc.fish -i s/fish/ghoti/g
./share/completions/passwd.fish -i s/fish/ghoti/g
./share/completions/patch.fish -i s/fish/ghoti/g
./share/completions/patool.fish -i s/fish/ghoti/g
./share/completions/pbget.fish -i s/fish/ghoti/g
./share/completions/pdfelatex.fish -i s/fish/ghoti/g
./share/completions/pdfetex.fish -i s/fish/ghoti/g
./share/completions/pdflatex.fish -i s/fish/ghoti/g
./share/completions/pdftex.fish -i s/fish/ghoti/g
./share/completions/pdftotext.fish -i s/fish/ghoti/g
./share/completions/perl.fish -i s/fish/ghoti/g
./share/completions/pfctl.fish -i s/fish/ghoti/g
./share/completions/pftp.fish -i s/fish/ghoti/g
./share/completions/pgrep.fish -i s/fish/ghoti/g
./share/completions/pg_dump.fish -i s/fish/ghoti/g
./share/completions/pg_dumpall.fish -i s/fish/ghoti/g
./share/completions/pg_restore.fish -i s/fish/ghoti/g
./share/completions/phpunit.fish -i s/fish/ghoti/g
./share/completions/pine.fish -i s/fish/ghoti/g
./share/completions/ping.fish -i s/fish/ghoti/g
./share/completions/pinky.fish -i s/fish/ghoti/g
./share/completions/pip.fish -i s/fish/ghoti/g
./share/completions/pip2.fish -i s/fish/ghoti/g
./share/completions/pip3.fish -i s/fish/ghoti/g
./share/completions/pipenv.fish -i s/fish/ghoti/g
./share/completions/pkg-config.fish -i s/fish/ghoti/g
./share/completions/pkg.fish -i s/fish/ghoti/g
./share/completions/pkgadd.fish -i s/fish/ghoti/g
./share/completions/pkgfile.fish -i s/fish/ghoti/g
./share/completions/pkginfo.fish -i s/fish/ghoti/g
./share/completions/pkgmk.fish -i s/fish/ghoti/g
./share/completions/pkgrm.fish -i s/fish/ghoti/g
./share/completions/pkg_add.fish -i s/fish/ghoti/g
./share/completions/pkg_delete.fish -i s/fish/ghoti/g
./share/completions/pkg_info.fish -i s/fish/ghoti/g
./share/completions/pkill.fish -i s/fish/ghoti/g
./share/completions/plutil.fish -i s/fish/ghoti/g
./share/completions/poff.fish -i s/fish/ghoti/g
./share/completions/pon.fish -i s/fish/ghoti/g
./share/completions/port.fish -i s/fish/ghoti/g
./share/completions/portmaster.fish -i s/fish/ghoti/g
./share/completions/ports.fish -i s/fish/ghoti/g
./share/completions/poweroff.fish -i s/fish/ghoti/g
./share/completions/powerpill.fish -i s/fish/ghoti/g
./share/completions/prevd.fish -i s/fish/ghoti/g
./share/completions/prime-run.fish -i s/fish/ghoti/g
./share/completions/prt-get.fish -i s/fish/ghoti/g
./share/completions/ps.fish -i s/fish/ghoti/g
./share/completions/ps2pdf.fish -i s/fish/ghoti/g
./share/completions/ps2pdf12.fish -i s/fish/ghoti/g
./share/completions/ps2pdf13.fish -i s/fish/ghoti/g
./share/completions/ps2pdf14.fish -i s/fish/ghoti/g
./share/completions/ps2pdfwr.fish -i s/fish/ghoti/g
./share/completions/psql.fish -i s/fish/ghoti/g
./share/completions/pstack.fish -i s/fish/ghoti/g
./share/completions/psub.fish -i s/fish/ghoti/g
./share/completions/pushd.fish -i s/fish/ghoti/g
./share/completions/pv.fish -i s/fish/ghoti/g
./share/completions/pydf.fish -i s/fish/ghoti/g
./share/completions/pyenv.fish -i s/fish/ghoti/g
./share/completions/pygmentize.fish -i s/fish/ghoti/g
./share/completions/python.fish -i s/fish/ghoti/g
./share/completions/python2.fish -i s/fish/ghoti/g
./share/completions/python3.fish -i s/fish/ghoti/g
./share/completions/pzstd.fish -i s/fish/ghoti/g
./share/completions/qubes-gpg-client.fish -i s/fish/ghoti/g
./share/completions/quilt.fish -i s/fish/ghoti/g
./share/completions/random.fish -i s/fish/ghoti/g
./share/completions/ranger.fish -i s/fish/ghoti/g
./share/completions/rbenv.fish -i s/fish/ghoti/g
